<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="10" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1281" started-at="2017-04-17T08:01:22Z" finished-at="2017-04-17T08:01:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1281" started-at="2017-04-17T08:01:22Z" finished-at="2017-04-17T08:01:23Z">
      <class name="com.epam.apartment.service.UserServiceTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="setUp" is-config="true" duration-ms="1079" started-at="2017-04-17T11:01:22Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="aithoriseUserUnexistedEmailTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="aithoriseUserUnexistedEmailTest" duration-ms="41" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aithoriseUserUnexistedEmailTest -->
        <test-method status="PASS" signature="authoriseUserSuccessTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="authoriseUserSuccessTest" duration-ms="3" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authoriseUserSuccessTest -->
        <test-method status="PASS" signature="changePswdSuccessTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="changePswdSuccessTest" duration-ms="3" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePswdSuccessTest -->
        <test-method status="PASS" signature="editProfileDuplicatedKeyExceptionTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="editProfileDuplicatedKeyExceptionTest" duration-ms="11" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <exception class="org.springframework.dao.DuplicateKeyException">
            <full-stacktrace>
              <![CDATA[org.springframework.dao.DuplicateKeyException
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.dao.DuplicateKeyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editProfileDuplicatedKeyExceptionTest -->
        <test-method status="PASS" signature="editProfileSuccessTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="editProfileSuccessTest" duration-ms="6" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editProfileSuccessTest -->
        <test-method status="PASS" signature="registerNewUserSuccessTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="registerNewUserSuccessTest" duration-ms="19" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUserSuccessTest -->
        <test-method status="PASS" signature="registerNewUserThrowDuplicatedKeyExceptionTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="registerNewUserThrowDuplicatedKeyExceptionTest" duration-ms="3" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <exception class="org.springframework.dao.DuplicateKeyException">
            <full-stacktrace>
              <![CDATA[org.springframework.dao.DuplicateKeyException
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.dao.DuplicateKeyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUserThrowDuplicatedKeyExceptionTest -->
        <test-method status="PASS" signature="registerNewUserUnmatchingPswdsTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="registerNewUserUnmatchingPswdsTest" duration-ms="2" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <exception class="com.epam.apartment.service.ServiceException">
            <full-stacktrace>
              <![CDATA[com.epam.apartment.service.ServiceException
	at com.epam.apartment.service.impl.UserServiceImpl.registerNewUser(UserServiceImpl.java:24)
	at com.epam.apartment.service.UserServiceTest.registerNewUserUnmatchingPswdsTest(UserServiceTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.epam.apartment.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUserUnmatchingPswdsTest -->
        <test-method status="PASS" signature="restorePswdMatchingPswdsTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="restorePswdMatchingPswdsTest" duration-ms="10" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restorePswdMatchingPswdsTest -->
        <test-method status="PASS" signature="restorePswdUnmatchingPswdsTest()[pri:0, instance:com.epam.apartment.service.UserServiceTest@482f8f11]" name="restorePswdUnmatchingPswdsTest" duration-ms="12" started-at="2017-04-17T11:01:23Z" finished-at="2017-04-17T11:01:23Z">
          <exception class="com.epam.apartment.service.ServiceException">
            <full-stacktrace>
              <![CDATA[com.epam.apartment.service.ServiceException
	at com.epam.apartment.service.impl.UserServiceImpl.restorePswd(UserServiceImpl.java:42)
	at com.epam.apartment.service.UserServiceTest.restorePswdUnmatchingPswdsTest(UserServiceTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.epam.apartment.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restorePswdUnmatchingPswdsTest -->
      </class> <!-- com.epam.apartment.service.UserServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
